### PR TITLE
print class level deprecation warning messages

### PR DESCRIPTION
**Pull request by ndushay**
connected to #3

@darrenleeweber 

figured out how to do class level deprecation with help from @atz.  Will cut final gem release after this is merged.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
OK, so this implies a semantic version bump to the major version num?  (i.e. it's a bit murky, because it's basically the same code, but the class name has changed so it's not backward compatible.)

**Comment by ndushay** [comment]
Well, the class name will still work - it just prints a deprecation warning.  So my inclination would be a minor version bump ... but I don't really care that much.

**Comment by atz** [comment]
My sentiment on this was "let the monkey-kludges burn".  Also, the audience for this gem is basically a handful of people we already know.

**Comment by cbeer** [comment]
I'd also note that, according to semver.org, before you hit `1.0.0`, you're free to change anything you want without bumping the major version. Certainly before you hit `0.1.0`, there's almost no obligation to do anything for your consumers (unless you want to.)

**Pull request merged**
